alldata <- read.csv("household_power_consumption.txt",sep=";", na.strings="?", colClasses=c("character", "character",rep("numeric", 7)))
subdata <- subset(alldata, Date == "2/2/2007" | Date == "1/2/2007")
rm(alldata)
timdata = transform(subdata, Date = as.Date(Date, format="%d/%m/%Y"), Time=strptime(paste(Date, Time), format="%d/%m/%Y %H:%M:%S"))
png(filename="plot3.png")
par(mfrow=c(1,1))
with(timdata, plot(Time, Sub_metering_1, type="l", ylab="Energy sub metering", xlab=""))
with(timdata, lines(Time, Sub_metering_2, col="red"))
with(timdata, lines(Time, Sub_metering_3, col="blue"))
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"))
dev.off()